---
- name: "basic auth for {{ nginx_site.key }}"
  no_log: true
  htpasswd:
    path: "/etc/nginx/auth/{{ nginx_site.key }}"
    create: yes
    name: "{{ item.name }}"
    password: "{{ item.password }}"
    state: "{{ item.state | default('present') }}"
  with_items: "{{ nginx_auth[nginx_site.key] }}"
  when:
    - nginx_auth[nginx_site.key] is defined

- name: "make {{ nginx_site.key }} available"
  template:
    src: "{{ nginx_site.value.template | default('sites-available/site-available.j2') }}"
    dest: "/etc/nginx/sites-available/{{ nginx_site.key }}"
  notify:
    - reload nginx

- name: "enable {{ nginx_site.key }}"
  file:
    src: "/etc/nginx/sites-available/{{ nginx_site.key }}"
    dest: "/etc/nginx/sites-enabled/{{ nginx_site.key }}"
    state: link
  notify:
    - reload nginx