---
- name: setup pre-requisites
  hosts: all
  become: yes
  roles:
    - docker
    - docker-compose

- name: add managers to the swarm
  hosts: managers
  become: yes
  roles:
    - docker-swarm-add-manager

- name: add workers to the swarm
  hosts: workers
  become: yes
  roles:
    - docker-swarm-add-worker

- name: deploy haproxy
  hosts: haproxy
  tasks:
    - include_vars: "{{playbook_dir}}/config.yml"
    - import_role:
        name: haproxy