---
- name: generate letsencrypt certificates
  hosts: haproxy
  become: true
  become_method: sudo
  tasks:
    - include_vars: "{{playbook_dir}}/config.yml"
    - import_role:
        name: letsencrypt
        
- name: deploy nginx
  hosts: haproxy
  become: true
  become_method: sudo
  tasks:
    - include_vars: "{{playbook_dir}}/config.yml"
    - import_role:
        name: nginx