---
- name: check if swarm has already been initialized
  shell: docker node ls
  register: swarm_status
  when: inventory_hostname == groups['managers'][0]
  ignore_errors: true

- name: initialize new docker swarm leader
  shell: docker swarm init --advertise-addr={{ inventory_hostname }}
  when: swarm_status.rc != 0 and inventory_hostname == groups['managers'][0]
  run_once: true

- name: get the manager join-token
  shell: docker swarm join-token --quiet manager
  when: inventory_hostname == groups['managers'][0]
  register: manager_token

- name: get the worker join-token
  when: inventory_hostname == groups['managers'][0]
  shell: docker swarm join-token --quiet worker
  register: worker_token

- name: docker node info
  docker_node_info:
    name: worker
  register: worker_status

- name: debug
  debug:
    msg: "{{ worker_status }}"

- name: debug worker token
  debug:
    msg: "{{ worker_token }}"

- name: debug manager token
  debug:
    msg: "{{ manager_token }}"
